#!/usr/bin/env node
// Reads packages/design/tokens/source.json → Questadi/App/DesignTokens.swift
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const tokens = JSON.parse(
  readFileSync(join(__dirname, '../../../packages/design/tokens/source.json'), 'utf8')
);

function hexToRGB(hex) {
  const h = hex.replace('#', '');
  return {
    r: (parseInt(h.slice(0, 2), 16) / 255).toFixed(4),
    g: (parseInt(h.slice(2, 4), 16) / 255).toFixed(4),
    b: (parseInt(h.slice(4, 6), 16) / 255).toFixed(4),
  };
}

function swiftColor(name, hex) {
  const { r, g, b } = hexToRGB(hex);
  return `    static let ${name} = Color(red: ${r}, green: ${g}, blue: ${b}, opacity: 1)`;
}

function buildSwift(t) {
  const lines = [
    `// Generated by apps/ios/scripts/generate-tokens.js — do not edit.`,
    `import SwiftUI`,
    ``,
    `enum BrandColor {`,
    `  enum Brand {`,
  ];

  for (const [shade, hex] of Object.entries(t.color.brand))
    lines.push(swiftColor(`_${shade}`, hex));

  lines.push(`  }`);
  lines.push(`  enum Neutral {`);

  for (const [shade, hex] of Object.entries(t.color.neutral))
    lines.push(swiftColor(`_${shade}`, hex));

  lines.push(`  }`);
  lines.push(`  enum Semantic {`);

  for (const [name, hex] of Object.entries(t.color.semantic))
    lines.push(swiftColor(name, hex));

  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`enum BrandFont {`);
  lines.push(`  static let base = "${t.typography.family.base.match(/'([^']+)'/)[1]}"`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`enum BrandRadius {`);

  for (const [name, value] of Object.entries(t.radius)) {
    const pts = name === 'full' ? 9999 : parseFloat(value);
    const swiftName = name.replace('2xl', 'xxl');
    lines.push(`  static let ${swiftName}: CGFloat = ${pts}`);
  }

  lines.push(`}`);
  lines.push(``);
  lines.push(`enum BrandSpacing {`);

  for (const [name, value] of Object.entries(t.spacing))
    lines.push(`  static let s${name}: CGFloat = ${parseFloat(value)}`);

  lines.push(`}`);
  return lines.join('\n');
}

writeFileSync(
  join(__dirname, '../Questadi/App/DesignTokens.swift'),
  buildSwift(tokens),
  'utf8'
);
console.log('✓ Questadi/App/DesignTokens.swift');
