// Generated by apps/ios/scripts/generate-tokens.js — do not edit.
import SwiftUI

enum BrandColor {
  enum Brand {
    static let _50 = Color(red: 1.0000, green: 0.9569, blue: 0.9333, opacity: 1)
    static let _100 = Color(red: 1.0000, green: 0.8863, blue: 0.8000, opacity: 1)
    static let _200 = Color(red: 1.0000, green: 0.7529, blue: 0.6000, opacity: 1)
    static let _300 = Color(red: 1.0000, green: 0.5843, blue: 0.4000, opacity: 1)
    static let _400 = Color(red: 1.0000, green: 0.4275, blue: 0.2000, opacity: 1)
    static let _500 = Color(red: 0.9608, green: 0.3294, blue: 0.0000, opacity: 1)
    static let _600 = Color(red: 0.8000, green: 0.2706, blue: 0.0000, opacity: 1)
    static let _700 = Color(red: 0.6392, green: 0.2196, blue: 0.0000, opacity: 1)
    static let _800 = Color(red: 0.4784, green: 0.1647, blue: 0.0000, opacity: 1)
    static let _900 = Color(red: 0.3216, green: 0.1098, blue: 0.0000, opacity: 1)
  }
  enum Neutral {
    static let _0 = Color(red: 1.0000, green: 1.0000, blue: 1.0000, opacity: 1)
    static let _50 = Color(red: 0.9804, green: 0.9804, blue: 0.9804, opacity: 1)
    static let _100 = Color(red: 0.9569, green: 0.9569, blue: 0.9569, opacity: 1)
    static let _200 = Color(red: 0.9098, green: 0.9098, blue: 0.9098, opacity: 1)
    static let _300 = Color(red: 0.8196, green: 0.8196, blue: 0.8196, opacity: 1)
    static let _400 = Color(red: 0.6392, green: 0.6392, blue: 0.6392, opacity: 1)
    static let _500 = Color(red: 0.4510, green: 0.4510, blue: 0.4510, opacity: 1)
    static let _600 = Color(red: 0.3216, green: 0.3216, blue: 0.3216, opacity: 1)
    static let _700 = Color(red: 0.2275, green: 0.2275, blue: 0.2275, opacity: 1)
    static let _800 = Color(red: 0.1490, green: 0.1490, blue: 0.1490, opacity: 1)
    static let _900 = Color(red: 0.1020, green: 0.1020, blue: 0.1020, opacity: 1)
    static let _950 = Color(red: 0.0510, green: 0.0549, blue: 0.0627, opacity: 1)
  }
  enum Semantic {
    static let success = Color(red: 0.1333, green: 0.7725, blue: 0.3686, opacity: 1)
    static let warning = Color(red: 0.9608, green: 0.6196, blue: 0.0431, opacity: 1)
    static let error = Color(red: 0.9373, green: 0.2667, blue: 0.2667, opacity: 1)
    static let info = Color(red: 0.2314, green: 0.5098, blue: 0.9647, opacity: 1)
  }
}

enum BrandFont {
  static let base = "Nunito"
}

enum BrandRadius {
  static let none: CGFloat = 0
  static let xs: CGFloat = 4
  static let sm: CGFloat = 8
  static let md: CGFloat = 12
  static let lg: CGFloat = 16
  static let xl: CGFloat = 20
  static let xxl: CGFloat = 28
  static let full: CGFloat = 9999
}

enum BrandSpacing {
  static let s0: CGFloat = 0
  static let s1: CGFloat = 4
  static let s2: CGFloat = 8
  static let s3: CGFloat = 12
  static let s4: CGFloat = 16
  static let s5: CGFloat = 20
  static let s6: CGFloat = 24
  static let s8: CGFloat = 32
  static let s10: CGFloat = 40
  static let s12: CGFloat = 48
  static let s16: CGFloat = 64
  static let s20: CGFloat = 80
  static let s24: CGFloat = 96
}