#!/usr/bin/env node
// Reads source.json → dist/tokens.css + dist/tokens.swift
// Run: node build.js

import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const tokens = JSON.parse(readFileSync(join(__dirname, 'source.json'), 'utf8'));

mkdirSync(join(__dirname, 'dist'), { recursive: true });

// ── CSS ───────────────────────────────────────────────────────────────────────

function buildCss(t) {
  const lines = [
    `@import url('https://fonts.googleapis.com/css2?family=Nunito:wght@400;500;600;700;800&display=swap');`,
    ``,
    `:root {`,
  ];

  for (const [shade, value] of Object.entries(t.color.brand))
    lines.push(`  --color-brand-${shade}: ${value};`);
  lines.push('');

  for (const [shade, value] of Object.entries(t.color.neutral))
    lines.push(`  --color-neutral-${shade}: ${value};`);
  lines.push('');

  for (const [name, value] of Object.entries(t.color.semantic))
    lines.push(`  --color-${name}: ${value};`);
  lines.push('');

  for (const [name, value] of Object.entries(t.typography.family))
    lines.push(`  --font-family-${name}: ${value};`);
  lines.push('');

  for (const [name, value] of Object.entries(t.typography.size))
    lines.push(`  --text-${name}: ${value};`);
  lines.push('');

  for (const [name, value] of Object.entries(t.typography.weight))
    lines.push(`  --font-${name}: ${value};`);
  lines.push('');

  for (const [name, value] of Object.entries(t.typography.leading))
    lines.push(`  --leading-${name}: ${value};`);
  lines.push('');

  for (const [name, value] of Object.entries(t.typography.tracking))
    lines.push(`  --tracking-${name}: ${value};`);
  lines.push('');

  for (const [name, value] of Object.entries(t.spacing))
    lines.push(`  --space-${name}: ${value};`);
  lines.push('');

  for (const [name, value] of Object.entries(t.radius))
    lines.push(`  --radius-${name}: ${value};`);
  lines.push('');

  for (const [name, value] of Object.entries(t.shadow))
    lines.push(`  --shadow-${name}: ${value};`);
  lines.push('');

  for (const [name, value] of Object.entries(t.duration))
    lines.push(`  --duration-${name}: ${value};`);
  lines.push('');

  for (const [name, value] of Object.entries(t.easing))
    lines.push(`  --easing-${name}: ${value};`);

  lines.push('');
  for (const [name, ref] of Object.entries(t.alias.light))
    lines.push(`  --${name}: ${resolveAlias(ref, t)};`);

  lines.push(`}`);
  lines.push(``);
  lines.push(`@media (prefers-color-scheme: dark) {`);
  lines.push(`  :root {`);
  for (const [name, ref] of Object.entries(t.alias.dark))
    lines.push(`    --${name}: ${resolveAlias(ref, t)};`);
  lines.push(`  }`);
  lines.push(`}`);

  return lines.join('\n');
}

function resolveAlias(ref, t) {
  const [group, shade] = ref.split('.');
  return t.color[group][shade];
}

// ── Swift ─────────────────────────────────────────────────────────────────────

function hexToRGB(hex) {
  const h = hex.replace('#', '');
  return {
    r: (parseInt(h.slice(0, 2), 16) / 255).toFixed(4),
    g: (parseInt(h.slice(2, 4), 16) / 255).toFixed(4),
    b: (parseInt(h.slice(4, 6), 16) / 255).toFixed(4),
  };
}

function swiftColor(name, hex) {
  const { r, g, b } = hexToRGB(hex);
  return `    static let ${name} = Color(red: ${r}, green: ${g}, blue: ${b}, opacity: 1)`;
}

function buildSwift(t) {
  const lines = [
    `// Generated by packages/design/tokens/build.js — do not edit.`,
    `import SwiftUI`,
    ``,
    `enum BrandColor {`,
    `  enum Brand {`,
  ];

  for (const [shade, hex] of Object.entries(t.color.brand))
    lines.push(swiftColor(`_${shade}`, hex));

  lines.push(`  }`);
  lines.push(`  enum Neutral {`);

  for (const [shade, hex] of Object.entries(t.color.neutral))
    lines.push(swiftColor(`_${shade}`, hex));

  lines.push(`  }`);
  lines.push(`  enum Semantic {`);

  for (const [name, hex] of Object.entries(t.color.semantic))
    lines.push(swiftColor(name, hex));

  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`enum BrandFont {`);
  lines.push(`  static let base = "Nunito"`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`enum BrandRadius {`);

  for (const [name, value] of Object.entries(t.radius)) {
    const pts = name === 'full' ? 9999 : parseFloat(value);
    const swiftName = name.replace('2xl', 'xxl');
    lines.push(`  static let ${swiftName}: CGFloat = ${pts}`);
  }

  lines.push(`}`);
  lines.push(``);
  lines.push(`enum BrandSpacing {`);

  for (const [name, value] of Object.entries(t.spacing))
    lines.push(`  static let s${name}: CGFloat = ${parseFloat(value)}`);

  lines.push(`}`);
  return lines.join('\n');
}

// ── Write ─────────────────────────────────────────────────────────────────────

writeFileSync(join(__dirname, 'dist', 'tokens.css'),   buildCss(tokens),   'utf8');
writeFileSync(join(__dirname, 'dist', 'tokens.swift'), buildSwift(tokens), 'utf8');

console.log('✓ dist/tokens.css');
console.log('✓ dist/tokens.swift');
